# General settings
[General]
# The offset above the entity's head at which the bubble renders
# Range: 0.0 ~ 10.0
YOffset = 1.0
# Render chat messages above players heads in a bubble
playerBubbles = true
# The maximum width of the bubble text before it wraps to a new line
# Range: 10 ~ 512
maxTextWidth = 100
# Offset the bubble text if the entity's name is rendered above their head
nameOffset = true
# Show the username of the player who sent the message in the bubble
showUsername = true
