[general]

[general.general]
# Always create full creative-mode chests when formed. Should not be used in survival worlds!
creativeChests = false
# If the interface input overlay should always be rendered on chests.
alwaysShowInterfaceOverlay = true
# Multiplier for the number of inventory slots for this chest material.
chestInventoryMaterialFactorDiamond = 2.0
# Multiplier for the number of inventory slots for this chest material.
chestInventoryMaterialFactorObsidian = 2.0
# If items should be ejected from the chests if one of the structure blocks are removed.
ejectItemsOnDestroy = false
# Multiplier for the number of inventory slots for this chest material.
chestInventoryMaterialFactorIron = 1.0
# Multiplier for the number of inventory slots for this chest material.
chestInventoryMaterialFactorWood = 0.25
# Multiplier for the number of inventory slots for this chest material.
chestInventoryMaterialFactorCopper = 0.75
# Multiplier for the number of inventory slots for this chest material.
chestInventoryMaterialFactorGold = 1.5
# If the higher tier metal variants (including diamond and obsidian) can be crafted.
metalVariants = false
# Multiplier for the number of inventory slots for this chest material.
chestInventoryMaterialFactorSilver = 1.75

[general.colossal_chest]
# If the chest should visually open when someone uses it.
chestAnimation = false

[core]

[core.general]
# If mod compatibility loader should crash hard if errors occur in that process.
crashOnModCompatCrash = false
# Maximum buffer byte size for adaptive inventory slots fragmentation.
maxPacketBufferSize = 20000
# If the recipe loader should crash when finding invalid recipes.
crashOnInvalidRecipe = false
# If an anonymous mod startup analytics request may be sent to our analytics service.
analytics = false
# If the version checker should be enabled.
versionChecker = false

[machine]

[machine.colossal_chest]
# The maximum size a colossal chest can have.
maxSize = 9
