# Maximum health of the common blob
# Range: > 0
commonBlobMaxHealth = 50
# Maximum health of the rare blob
# Range: > 0
rareBlobMaxHealth = 500
# Maximum health of the legendary blob
# Range: > 0
legendaryBlobMaxHealth = 1500
