##########
# Copyright (c) 2024 Darkosto Entertainment LLC
#
# All rights reserved.
##########


#General configuration options.
[General]
	#Enable tag list tooltips for blocks/items?
	tagTooltips = true
	#Enable NBT tooltips for items?
	nbtTooltips = false

